# Aliases
alias ls='ls --color=auto'
alias ...='cd ../..'
alias g='git'
alias grep='grep --color=auto'
alias :q='exit'
alias ssh-public-key='cat ~/.ssh/id_rsa.pub'
alias vim='nvim'
alias whoneeds='pacman -Qi'
alias md='mkdir -p'
alias rd='rmdir'
alias hib='systemctl hibernate'
alias c='clear'
alias tlmgr='tlmgr --usermode'
